Pages/Day.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Globalization;

namespace Pickle.Pages
{
    public class DayModel : PageModel
    {
        public enum Availability
        {
            Locked,
            Missing,
            Available
        }
        public int Year { get; private set; }
        public int Month { get; private set; }
        public int Day { get; private set; }

        public bool IsLocked { get; private set; }
        public string? FileExtension { get; private set; }

        private Files Files { get; }

        public DayModel(Files files)
        {
            Files = files ?? throw new ArgumentNullException(nameof(files));
        }

        public IActionResult OnGet()
        {
            var yearStr = RouteData.Values["year"];
            var monthStr = RouteData.Values["month"];
            var dayStr = RouteData.Values["day"];

            var isValid = DateTime.TryParse($"{yearStr}-{monthStr}-{dayStr} 00:00:00", CultureInfo.InvariantCulture, DateTimeStyles.None, out var date);
            if (!isValid)
                return Redirect("/");

            IsLocked = date > DateTime.Today;
            if (!IsLocked)
                FileExtension = Files.GetFileExtension(date);

            Year = date.Year;
            Month = date.Month;
            Day = date.Day;
            return Page();
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Pickle.Pages
{
    public class IndexModel : PageModel
    {
        public IActionResult OnGet()
        {
            var now = DateTime.UtcNow.Date;
            return Redirect($"/{now.Year}/{now.Month}");
        }
    }
}

Pages/Month.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Globalization;

namespace Pickle.Pages
{
    public class MonthModel : PageModel
    {
        public int Year { get; private set; }
        public int Month { get; private set; }

        public bool IsAvailable { get; private set; }

        public IActionResult OnGet()
        {
            var yearStr = RouteData.Values["year"];
            var monthStr = RouteData.Values["month"];

            var isValid = DateTime.TryParse($"{yearStr}-{monthStr}-01 00:00:00", CultureInfo.InvariantCulture, DateTimeStyles.None, out var date);
            if (!isValid)
                return Redirect("/");

            IsAvailable = date >= DateTime.Today;
            Year = date.Year;
            Month = date.Month;
            return Page();
        }
    }
}

Pages/Shared/Components/NavBar/NavBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Pickle.Pages.Shared.Components.NavBar;

public class NavBarViewComponent : ViewComponent
{
    public IViewComponentResult Invoke()
    {
        return View();
    }
}

Pages/Year.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Globalization;

namespace Pickle.Pages
{
    public class YearModel : PageModel
    {
        public int Year { get; private set; }

        public bool IsAvailable { get; private set; }

        public IActionResult OnGet()
        {
            var yearStr = RouteData.Values["year"];

            var isValid = DateTime.TryParse($"{yearStr}-01-01 00:00:00", CultureInfo.InvariantCulture, DateTimeStyles.None, out var date);
            if (!isValid)
                return Redirect("/");

            IsAvailable = date >= DateTime.Today;
            Year = date.Year;
            return Page();
        }
    }
}

Pages/Day.cshtml
@page "/{year}/{month}/{day}"
@model DayModel
@{
    ViewData["Title"] = new DateTime(Model.Year, Model.Month, Model.Day).ToString("D");
}

<div class="d-flex justify-content-between h4 m-0 mb-4">
	@{
		var lastDay = new DateTime(Model.Year, Model.Month, Model.Day).AddDays(-1);
		var nextDay = new DateTime(Model.Year, Model.Month, Model.Day).AddDays(1);
		<a class="d-flex flex-row align-items-center gap-2 text-decoration-none highlight" href="/@lastDay.Year/@lastDay.Month/@lastDay.Day">
			<i class="fa-solid fa-angle-left mt-1"></i>
			@lastDay.ToString("dddd dd")
		</a>
		<nav aria-label="breadcrumb">
			<ol class="breadcrumb mb-1">
				<li class="breadcrumb-item">
					<a href="/@Model.Year/" class="text-decoration-none highlight">
						@Model.Year
					</a>
				</li>
				<li class="breadcrumb-item">
					<a href="/@Model.Year/@Model.Month" class="text-decoration-none highlight">
						@(new DateTime(Model.Year, Model.Month, 1).ToString("MMMM"))
					</a>
				</li>
				<li class="breadcrumb-item active" aria-current="page">
					@(new DateTime(Model.Year, Model.Month, Model.Day).ToString("dddd dd"))
				</li>
			</ol>
		</nav>
		<a class="d-flex flex-row align-items-center gap-2 text-decoration-none highlight" href="/@nextDay.Year/@nextDay.Month/@nextDay.Day">
			@nextDay.ToString("dddd dd")
			<i class="fa-solid fa-angle-right mt-1"></i>
		</a>
	}
</div>


@if (Model.IsLocked)
{
    <div class="text-center fs-1 highlight mt-5">
		<i class="fa-solid fa-lock"></i>
	</div>
    <div class="text-center fs-3 highlight">
		Come back later
	</div>
}
else if (Model.FileExtension == ".png"
		 || Model.FileExtension == ".jpg"
		 || Model.FileExtension == ".jpeg"
		 || Model.FileExtension == ".gif")
{
	<div class="container d-flex justify-content-center flex-grow-0">
		<img src="@($"/_content/{Model.Year}/{Model.Month:D2}/{Model.Day:D2}{Model.FileExtension}")" style="min-height: 600px; height: calc(100vh - 200px);" />
	</div>
}
else if (Model.FileExtension == ".mp4")
{
	<div class="container d-flex justify-content-center flex-grow-0">
		<video controls="" src="@($"/_content/{Model.Year}/{Model.Month:D2}/{Model.Day:D2}{Model.FileExtension}")" autoplay="" style="min-height: 600px; height: calc(100vh - 200px);"></video>
	</div>
}
else if(Model.FileExtension == null)
{
    <div class="text-center fs-1 highlight mt-5">
		:(
	</div>
    <div class="text-center fs-3">
		We don't have anything to show today - sorry!
	</div>
}
else
{
    <div class="text-center fs-1 highlight mt-5">
		<i class="fa-solid fa-question"></i>
	</div>
    <div class="text-center fs-3">
		We're not sure how to show this file
	</div>
    <div class="text-center fs-5">
		<a class="highlight text-decoration-none" href="@($"/_content/{Model.Year}/{Model.Month:D2}/{Model.Day:D2}{Model.FileExtension}")">
			Go directly to file
		</a>
	</div>
}

Pages/Index.cshtml
@page
@model IndexModel

Pages/Month.cshtml
@page "/{year}/{month}"
@model Pickle.Pages.MonthModel
@{
	ViewData["Title"] = new DateTime(Model.Year, Model.Month, 1).ToString("Y");
}

<div class="d-flex justify-content-between h4 m-0">
	@{
		var lastMonth = new DateTime(Model.Year, Model.Month, 1).AddMonths(-1);
		var nextMonth = new DateTime(Model.Year, Model.Month, 1).AddMonths(1);
		<a class="d-flex flex-row align-items-center gap-2 text-decoration-none highlight" href="/@lastMonth.Year/@lastMonth.Month">
			<i class="fa-solid fa-angle-left mt-1"></i>
			@lastMonth.ToString("MMMM")
		</a>
		<nav aria-label="breadcrumb">
			<ol class="breadcrumb mb-1">
				<li class="breadcrumb-item">
					<a href="/@Model.Year/" class="text-decoration-none highlight">
						@Model.Year
					</a>
				</li>
				<li class="breadcrumb-item active" aria-current="page">
					@(new DateTime(Model.Year, Model.Month, 1).ToString("MMMM"))
				</li>
			</ol>
		</nav>
		<a class="d-flex flex-row align-items-center gap-2 text-decoration-none highlight" href="/@nextMonth.Year/@nextMonth.Month">
			@nextMonth.ToString("MMMM")
			<i class="fa-solid fa-angle-right mt-1"></i>
		</a>
	}
</div>

<div class="row my-4 px-1">
	@{
		for (int i = 1; i <= 7; i++)
		{
			<div class="col-week p-2">
				<div class="card border-0">
					<div class="card-body text-center p-0">
						@(new DateTime(1, 1, i).ToString("dddd"))
					</div>
				</div>
			</div>
		}
		var boxes = 0;
		var startOfMonth = new DateTime(Model.Year, Model.Month, 1);
		for (int i = 1; i <= (int)startOfMonth.DayOfWeek - 1; i++)
		{
			boxes++;
			<div class="col-week p-2">
				<div class="card">
					<div class="card-body">
						&nbsp;
					</div>
				</div>
			</div>
		}
		for (int i = 1; i <= DateTime.DaysInMonth(Model.Year, Model.Month); i++)
		{
			boxes++;
			var now = DateTime.Now.Date;
			var day = new DateTime(Model.Year, Model.Month, i);
			<div class="col-week p-2">
				<a class="text-decoration-none highlight" href="/@Model.Year/@Model.Month/@i">
					<div class="card">
						<div class="card-body h5 mb-0 @(day > now ? "text-muted" : "")">
							@(day.ToString("dd"))
						</div>
					</div>
				</a>
			</div>
		}
		for (int i = 1; i <= (7 - (boxes % 7)) % 7; i++)
		{
			<div class="col-week p-2">
				<div class="card">
					<div class="card-body">
						&nbsp;
					</div>
				</div>
			</div>
		}
	}
</div>

Pages/Shared/Components/NavBar/Default.cshtml
@{
	DateTime now = DateTime.Now;
}

<div class="container">
	<header class="row py-3 mb-4 border-bottom">
		<div class="col-0 col-md-3 col-lg-4"></div>
		<a href="/" class="col-6 col-md-6 col-lg-4 d-flex justify-content-center align-items-center mb-0 h4 text-dark text-decoration-none">
			Pickle
		</a>
		<div class="col-6 col-md-3 col-lg-4 d-flex justify-content-end align-items-center">
			<a href="/@now.Year/@now.Month/@now.Day" class="nav-link highlight">Today</a>
		</div>
	</header>
</div>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pickle</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/css/bootstrap.min.css" integrity="sha512-GQGU0fMMi238uA+a/bdWJfpUGKUkBdgfFdgBm72SUQ6BeyWjoY/ton0tEjH+OSH9iP4Dfh+7HM0I9f5eR0L/4w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body class="vh-100 d-flex flex-column">
    <vc:nav-bar />
    <main class="container">
        @RenderBody()
    </main>
</body>
</html>

Pages/Year.cshtml
@page "/{year}"
@model Pickle.Pages.YearModel
@{
	ViewData["Title"] = Model.Year.ToString();
}

<div class="d-flex justify-content-between h4 m-0">
	<a class="d-flex flex-row align-items-center gap-2 text-decoration-none highlight" href="/@(Model.Year - 1)/">
		<i class="fa-solid fa-angle-left mt-1"></i>
		@(Model.Year - 1)
	</a>
	<nav aria-label="breadcrumb">
		<ol class="breadcrumb mb-1">
			<li class="breadcrumb-item active" aria-current="page">
				@Model.Year
			</li>
		</ol>
	</nav>
	<a class="d-flex flex-row align-items-center gap-2 text-decoration-none highlight" href="/@(Model.Year + 1)/">
		@(Model.Year + 1)
		<i class="fa-solid fa-angle-right mt-1"></i>
	</a>
</div>

<div class="row my-4 px-1">
	@for (int i = 1; i <= 12; i++)
	{
		var now = DateTime.Now.Date;
		var month = new DateTime(Model.Year, i, 1);
		<div class="col-6 col-sm-4 col-md-3 col-lg-2 p-2">
			<a class="text-decoration-none highlight" href="/@Model.Year/@i">
				<div class="card">
					<div class="card-body h5 mb-0 @(month > now ? "text-muted" : "")">
						@(month.ToString("MMMM"))
					</div>
				</div>
			</a>
		</div>
	}
</div>